#pragma once

typedef int word;

#define WORD_LENGTH 16
#define SPACE 65536
#define NUM_REGISTER 8
#define REGISTER_ADDRESSABILITY 16


#define TRAP_VECTORTABLE_START 0x0000
#define TRAP_VECTORTABLE_END 0x00FF

#define INTERRUPT_VECTORTABLE_STRAT 0x0100
#define INTERRUPT_VECTORTABLE_END 0x01FF

#define OPERATINGSYSTEM_SUPERVISORSTACK_START 0x0200
#define OPERATINGSYSTEM_SUPERVISORSTACK_END 0x2FFF

#define USERSPACE_START 0x3000
#define USERSPACE_END 0xFDFF

#define DEVICEREGISTER_ADDRESSES_START 0xFE00
#define DEVICEREGISTER_ADDRESSES_END 0xFFFF